#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

# Conventional commit message validation
npx --no-install commitlint --edit "$1"
set -e # Exit immediately if any command fails

echo '🏗️👷 Styling, testing and building your project before committing'

npm run check-format ||
(
    echo 'Your code has some styling issues.
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)
# Check ESLint Standards
npm run check-lint ||
(
        echo '👋😤 Please fix your code syntax and semantics. 👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo '❌ Failed Type check. ❌
            Are you seriously trying to write that? Make the changes required above.'
    false;
)


# If everything passes... Now we can commit
echo 'Alright... Code looks good to me... Trying to build now. 🤔'

npm run build ||
(
    echo '❌👷🔨❌ Error... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why. 
    '
    false;
)

# If everything passes... Now we can commit
echo '✅✅ You win this time... I am committing this now. ✅✅'npx --no -- commitlint --edit $1
